2025-01-12 16:10:20.301 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration pirateweather which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-12 16:10:20.302 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration birdbuddy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-12 16:10:20.303 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-12 16:10:20.304 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration nintendo_parental which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-12 16:10:20.305 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration samsungtv_smart which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-12 16:10:20.305 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration browser_mod which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-12 16:10:20.306 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-12 16:10:20.308 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration icloud3 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-12 16:10:20.309 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration asusrouter which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-01-12 16:10:34.771 ERROR (MainThread) [homeassistant.components.select] Error while setting up tesla_fleet platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 374, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 641, in async_add_entities
    for entity in new_entities:
                  ^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tesla_fleet/select.py", line 95, in <genexpr>
    TeslaFleetWheelHeaterSelectEntity(vehicle, entry.runtime_data.scopes)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tesla_fleet/select.py", line 176, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        data,
        ^^^^^
        "climate_state_steering_wheel_heat_level",
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/components/tesla_fleet/entity.py", line 115, in __init__
    super().__init__(data.coordinator, data.api, key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/tesla_fleet/entity.py", line 49, in __init__
    self._async_update_attrs()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/components/tesla_fleet/select.py", line 188, in _async_update_attrs
    self._attr_current_option = self._attr_options[value]
                                ~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
2025-01-12 16:10:59.117 ERROR (MainThread) [frontend.js.modern.202501090] Uncaught error from Chrome 131.0.0.0 on Windows 10
TypeError: Cannot use 'in' operator to search for 'service' in p
action.map (src/data/script.ts:418:6)
_serviceDataChanged (src/panels/developer-tools/action/developer-tools-action.ts:547:6)
_yamlChanged (src/panels/developer-tools/action/developer-tools-action.ts:510:9)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
load (src/components/ha-yaml-editor.ts:153:14)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
Number (src/components/ha-code-editor.ts:328:14)
listener (node_modules/@codemirror/view/dist/index.js:7585:20)
2025-01-12 16:10:59.117 ERROR (MainThread) [frontend.js.modern.202501090] Uncaught error from Chrome 131.0.0.0 on Windows 10
TypeError: Cannot use 'in' operator to search for 'service' in pu
action.map (src/data/script.ts:418:6)
_serviceDataChanged (src/panels/developer-tools/action/developer-tools-action.ts:547:6)
_yamlChanged (src/panels/developer-tools/action/developer-tools-action.ts:510:9)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
load (src/components/ha-yaml-editor.ts:153:14)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
Number (src/components/ha-code-editor.ts:328:14)
listener (node_modules/@codemirror/view/dist/index.js:7585:20)
2025-01-12 16:10:59.117 ERROR (MainThread) [frontend.js.modern.202501090] Uncaught error from Chrome 131.0.0.0 on Windows 10
TypeError: Cannot use 'in' operator to search for 'service' in pus
action.map (src/data/script.ts:418:6)
_serviceDataChanged (src/panels/developer-tools/action/developer-tools-action.ts:547:6)
_yamlChanged (src/panels/developer-tools/action/developer-tools-action.ts:510:9)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
load (src/components/ha-yaml-editor.ts:153:14)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
Number (src/components/ha-code-editor.ts:328:14)
listener (node_modules/@codemirror/view/dist/index.js:7585:20)
2025-01-12 16:10:59.118 ERROR (MainThread) [frontend.js.modern.202501090] Uncaught error from Chrome 131.0.0.0 on Windows 10
TypeError: Cannot use 'in' operator to search for 'service' in push
action.map (src/data/script.ts:418:6)
_serviceDataChanged (src/panels/developer-tools/action/developer-tools-action.ts:547:6)
_yamlChanged (src/panels/developer-tools/action/developer-tools-action.ts:510:9)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
load (src/components/ha-yaml-editor.ts:153:14)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
Number (src/components/ha-code-editor.ts:328:14)
listener (node_modules/@codemirror/view/dist/index.js:7585:20)
2025-01-12 16:11:03.054 ERROR (MainThread) [frontend.js.modern.202501090] Uncaught error from Chrome 131.0.0.0 on Windows 10
TypeError: Cannot use 'in' operator to search for 'service' in pus
action.map (src/data/script.ts:418:6)
_serviceDataChanged (src/panels/developer-tools/action/developer-tools-action.ts:547:6)
_yamlChanged (src/panels/developer-tools/action/developer-tools-action.ts:510:9)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
load (src/components/ha-yaml-editor.ts:153:14)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
Number (src/components/ha-code-editor.ts:328:14)
listener (node_modules/@codemirror/view/dist/index.js:7585:20)
2025-01-12 16:11:03.252 ERROR (MainThread) [frontend.js.modern.202501090] Uncaught error from Chrome 131.0.0.0 on Windows 10
TypeError: Cannot use 'in' operator to search for 'service' in pu
action.map (src/data/script.ts:418:6)
_serviceDataChanged (src/panels/developer-tools/action/developer-tools-action.ts:547:6)
_yamlChanged (src/panels/developer-tools/action/developer-tools-action.ts:510:9)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
load (src/components/ha-yaml-editor.ts:153:14)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
Number (src/components/ha-code-editor.ts:328:14)
listener (node_modules/@codemirror/view/dist/index.js:7585:20)
2025-01-12 16:11:03.431 ERROR (MainThread) [frontend.js.modern.202501090] Uncaught error from Chrome 131.0.0.0 on Windows 10
TypeError: Cannot use 'in' operator to search for 'service' in p
action.map (src/data/script.ts:418:6)
_serviceDataChanged (src/panels/developer-tools/action/developer-tools-action.ts:547:6)
_yamlChanged (src/panels/developer-tools/action/developer-tools-action.ts:510:9)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
load (src/components/ha-yaml-editor.ts:153:14)
call (src/lit-html.ts:2018:28)
dispatchEvent (src/common/dom/fire_event.ts:75:7)
Number (src/components/ha-code-editor.ts:328:14)
listener (node_modules/@codemirror/view/dist/index.js:7585:20)
2025-01-12 16:11:24.155 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `/bin /bash pushupdates.sh`, return code: 126
NoneType: None
2025-01-12 16:14:32.568 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 380, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "aiohttp/_http_parser.pyx", line 558, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Pause on PRI/Upgrade:

    b''
      ^
2025-01-12 16:18:15.373 ERROR (MainThread) [homeassistant.components.script.announce_candy_has_arrived] Announce - Candy Has Arrived: Error executing script. Invalid data for call_service at pos 5: expected float for dictionary value @ data['volume_level']
2025-01-12 16:18:15.374 ERROR (MainThread) [homeassistant.components.automation.announce_candy_has_arrived] Announce - Candy Has Arrived: Error executing script. Invalid data for call_service at pos 1: expected float for dictionary value @ data['volume_level']
2025-01-12 16:18:15.375 ERROR (MainThread) [homeassistant.components.automation.announce_candy_has_arrived] Error while executing automation automation.announce_candy_has_arrived: expected float for dictionary value @ data['volume_level']
2025-01-12 16:20:32.874 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:32.874 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:33.064 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:33.064 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:33.451 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:33.451 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:33.887 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:33.887 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:34.099 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:34.100 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:34.363 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:34.363 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:34.901 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:34.901 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:35.175 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:35.175 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:35.422 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:35.422 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:35.655 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:35.655 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:36.103 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:36.103 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:36.736 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:36.736 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:37.043 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:37.043 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:37.243 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:37.244 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:37.673 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:37.674 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:37.913 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:37.914 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:38.279 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:38.280 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:38.555 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:38.555 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:38.851 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:38.851 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:39.113 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Collect Bird Buddy Postcard: Error executing script. Invalid data for call_service at pos 1: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:20:39.113 ERROR (MainThread) [homeassistant.components.automation.collect_bird_buddy_postcard] Error while executing automation automation.collect_bird_buddy_postcard: value should be a string for dictionary value @ data['device_id']
2025-01-12 16:22:43.070 ERROR (MainThread) [homeassistant.components.shell_command] Error running command: `/bin /bash pushupdates.sh`, return code: 126
NoneType: None
